on:
  workflow_dispatch:
  push:
    branches:
      - main

name: fox32 Unstable - Linux

jobs:
  fox32-unstable-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check out fox32core
        uses: actions/checkout@v2
        with:
          repository: fox32-arch/fox32core
          path: ./fox32core

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install libgtk-3-dev and libasound2-dev
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libasound2-dev

      - name: Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: fox32
          path: target/release/fox32
